2022-04-06 22:00:05,807 | INFO | Running AlgoBot...
2022-04-06 22:00:15,184 | WARNING | Error: Traceback (most recent call last):
  File "/home/pi/cryptobot/main.py", line 158, in <module>
    main()
  File "/home/pi/cryptobot/main.py", line 141, in main
    handle_update_message(bot)
  File "/home/pi/cryptobot/main.py", line 122, in handle_update_message
    handle_buy_order_message()
TypeError: handle_buy_order_message() missing 1 required positional argument: 'bot'

